### ISSUE TITLE
安装包安装完成之后，有安装完成事件吗？

### ISSUE THREAD

**Issue by kefeibuhuifei** [QDMarkMan/electron-builder-start#1]
我想在builder打包的安装包安装完成之后，去卸载一个不是用electron开发的程序，我是应该在nsis的脚本中写吗？  还是electron有这个事件？

**Comment by QDMarkMan** [comment]
这个是要在nsis脚本中写的， 你可以看看`Function .onInstSuccess`这个事件是否满足你的需求。

**Comment by kefeibuhuifei** [comment]
> 这个是要在nsis脚本中写的， 你可以看看`Function .onInstSuccess`这个事件是否满足你的需求。

好的谢谢，对nsis不太熟悉，我去看看nsis脚本怎么写~
